Admin user
wolox-training/yn-express-js pull request #10
Opened 2019-08-02 15:39 UTC by YesicaNavaB

## Summary

Administrator user

## Trello Card

https://trello.com/c/XZnT0OVr

2019-08-02 19:10 UTC, jersonlopez requested changes

2019-08-02 19:10 UTC, jersonlopez commented on app/controllers/users.js
> +    .then(() => {
remove brackets and return

2019-08-05 16:55 UTC, jersonlopez requested changes

2019-08-05 16:55 UTC, jersonlopez commented on app/middlewares/users.js
> +      throw error.databaseError('You do not have permissions to perform this operation');
is this an database error?

2019-08-05 16:55 UTC, jersonlopez commented on app/middlewares/users.js
> +    return next();
unnecessary return

2019-08-05 16:55 UTC, jersonlopez commented on app/services/users.js
> +  });
Missing .catch, what happens if the db or findOne fails?

2019-08-05 16:55 UTC, jersonlopez commented on test/users.test.js
> +  });
remember \n jajja :D

2019-08-05 16:55 UTC, jersonlopez commented on test/utils.test.js
> +  factory.create('User', { name, lastName, email, password, administrator }).then(user => user);
what is doing the .then?

2019-08-05 18:20 UTC, YesicaNavaB commented on test/utils.test.js
> +  factory.create('User', { name, lastName, email, password, administrator }).then(user => user);
Nothing :fearful:

2019-08-05 18:39 UTC, jersonlopez approved these changes
good job!! 💯 🥇

2019-08-05 18:49 UTC, merged