Disable all sessions
wolox-training/yn-express-js pull request #15
Opened 2019-08-13 19:30 UTC by YesicaNavaB

## Summary

Disable all sessions

## Trello Card

https://trello.com/c/yeSGiWhs

2019-08-15 16:21 UTC, jersonlopez requested changes

2019-08-15 16:21 UTC, jersonlopez commented on app/services/users.js
> +    logger.error(`Could not update user: ${err}`);
which user? what do you think about put the email in the log?

2019-08-15 16:21 UTC, jersonlopez commented on app/services/users.js
> +      if (result.count === 1) {
unnecessary condition, everything you put out of the first condition will be executed if this fails

2019-08-15 16:21 UTC, jersonlopez commented on test/albums.test.js
> +      dateToken: 1565721770
This field cannot be null? check it in the rest of the tests

2019-08-15 16:54 UTC, YesicaNavaB commented on app/services/users.js
> +    logger.error(`Could not update user: ${err}`);
ok!

2019-08-15 16:55 UTC, YesicaNavaB commented on app/services/users.js
> +      if (result.count === 1) {
ok!

2019-08-15 16:55 UTC, YesicaNavaB commented on test/albums.test.js
> +      dateToken: 1565721770
ok!

2019-08-21 14:23 UTC, jersonlopez approved these changes

2019-08-21 14:27 UTC, merged