Session expires
wolox-training/yn-express-js pull request #16
Opened 2019-08-14 21:11 UTC by YesicaNavaB

## Summary

Session expires

## Trello Card

https://trello.com/c/yeSGiWhs

2019-08-15 16:31 UTC, jersonlopez requested changes

2019-08-15 16:31 UTC, jersonlopez commented on test/utils.test.js
>  exports.token =
remove unncessary variable

2019-08-15 16:31 UTC, jersonlopez commented on test/users.test.js
> +        .post('/users/sessions')
good solution! 🥇

2019-08-15 16:31 UTC, jersonlopez commented on test/sessions.test.js
> +          delay(3000).then(() => {
i suggest you only 2000

2019-08-15 16:31 UTC, jersonlopez commented on test/sessions.test.js
> +  it('should not start navigation because the token expired', done => {
change description please

2019-08-20 01:41 UTC, YesicaNavaB commented on test/utils.test.js
>  exports.token =
ok!

2019-08-20 01:52 UTC, YesicaNavaB commented on test/sessions.test.js
> +          delay(3000).then(() => {
ok!

2019-08-20 01:53 UTC, YesicaNavaB commented on test/sessions.test.js
> +  it('should not start navigation because the token expired', done => {
ok!

2019-08-21 15:04 UTC, jersonlopez requested changes

2019-08-21 15:04 UTC, jersonlopez commented on test/fixture/albumPhotos.js
> +  all: albumsPhotos
if is never used, remove it please

2019-08-21 15:04 UTC, jersonlopez commented on test/__mocks__/request-promise.js
>  const album = {
it should also be in the fixtures

2019-08-21 15:25 UTC, YesicaNavaB commented on test/__mocks__/request-promise.js
>  const album = {
ok!

2019-08-21 15:25 UTC, YesicaNavaB commented on test/fixture/albumPhotos.js
> +  all: albumsPhotos
ok!

2019-08-21 15:31 UTC, jersonlopez approved these changes
good job yes!! finally finished your training 💯 💯 💯

2019-08-21 15:34 UTC, merged